"""Apache Avro schema export for datalasi DataContracts."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from datalasi.core.contract import DataContract, Field


def to_avro_schema(contract: DataContract) -> dict[str, Any]:
    """Convert a :class:`~datalasi.core.contract.DataContract` to an Avro schema.

    The returned dict is JSON-serialisable and represents a named Avro
    ``record`` type compatible with the Apache Avro specification.

    Type mappings:

    ============  =========================================
    datalasi      Avro
    ============  =========================================
    Int32         ``"int"``
    Int64         ``"long"``
    Float64       ``"double"``
    String        ``"string"``
    Boolean       ``"boolean"``
    Date          ``{"type": "int", "logicalType": "date"}``
    Timestamp     ``{"type": "long", "logicalType": "timestamp-millis"}``
    Enum          ``{"type": "enum", "symbols": [...]}``
    ============  =========================================

    Nullable fields use the Avro union ``["null", <type>]`` convention
    (``null`` first, as required by the Avro spec for optional fields).
    """
    avro_fields = []
    for col_name, field in contract.schema.items():
        avro_field: dict[str, Any] = {
            "name": col_name,
            "type": _field_to_avro_type(field),
        }
        if field.description:
            avro_field["doc"] = field.description
        avro_fields.append(avro_field)

    return {
        "type": "record",
        "name": contract.name,
        "namespace": "datalasi.contracts",
        "doc": contract.description or f"Generated by datalasi from contract v{contract.version}",
        "fields": avro_fields,
    }


def _field_to_avro_type(field: Field) -> Any:
    from datalasi.core.types import (
        Boolean,
        Date,
        Enum,
        Float64,
        Int32,
        Int64,
        Timestamp,
    )

    t = field.type

    if isinstance(t, Int32):
        avro_type: Any = "int"
    elif isinstance(t, Int64):
        avro_type = "long"
    elif isinstance(t, Float64):
        avro_type = "double"
    elif isinstance(t, Boolean):
        avro_type = "boolean"
    elif isinstance(t, Date):
        avro_type = {"type": "int", "logicalType": "date"}
    elif isinstance(t, Timestamp):
        avro_type = {"type": "long", "logicalType": "timestamp-millis"}
    elif isinstance(t, Enum):
        avro_type = {
            "type": "enum",
            "name": f"{field.name}_type",
            "symbols": list(t.allowed_values),
        }
    else:
        avro_type = "string"

    if field.nullable:
        return ["null", avro_type]

    return avro_type
