"""Pydantic model generation from datalasi DataContracts.

Two modes:
- :func:`to_pydantic_source` — returns a Python source string suitable for
  saving to a ``.py`` file and committing to your codebase.
- :func:`to_pydantic_model` — returns a live Pydantic ``BaseModel`` class
  you can import and use immediately (requires pydantic installed).
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from datalasi.core.contract import DataContract, Field


# ---------------------------------------------------------------------------
# Source-code generation
# ---------------------------------------------------------------------------


def to_pydantic_source(contract: DataContract) -> str:
    """Generate a Pydantic ``BaseModel`` source file from *contract*.

    The returned string is valid Python that can be written to a ``.py`` file.
    It targets **Pydantic v2** with ``from __future__ import annotations`` for
    Python 3.9+ compatibility.

    Type mappings:

    ============  =================  ====================================
    datalasi      Python annotation  Pydantic validators
    ============  =================  ====================================
    Int64 / Int32 ``int``            ``ge=``, ``le=``
    Float64       ``float``          ``ge=``, ``le=``
    String        ``str``            ``max_length=``, ``pattern=``
    Boolean       ``bool``           —
    Date          ``datetime.date``  —
    Timestamp     ``datetime.datetime`` —
    Enum          ``Literal[...]``   —
    ============  =================  ====================================

    Nullable fields become ``T | None = None`` (or ``Field(None, ...)`` when
    validators are present). Non-nullable fields are required by default.

    Example::

        src = to_pydantic_source(contract)
        Path("models/transactions.py").write_text(src)
    """
    class_name = _to_class_name(contract.name)

    field_lines: list[str] = []
    needs_datetime = False
    needs_literal = False
    needs_field = False

    for col_name, field in contract.schema.items():
        annotation, default_expr = _annotation_and_default(field)
        needs_datetime = needs_datetime or "datetime." in annotation
        needs_literal = needs_literal or annotation.startswith("Literal")
        needs_field = needs_field or (
            default_expr is not None and default_expr.startswith("Field(")
        )
        if default_expr is None:
            field_lines.append(f"    {col_name}: {annotation}")
        else:
            field_lines.append(f"    {col_name}: {annotation} = {default_expr}")

    # ---- Build import block ----
    import_lines: list[str] = ['"""Auto-generated by datalasi.']
    import_lines += [
        "",
        f"Source contract: {contract.name!r} v{contract.version}",
        "Do not edit manually.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    if needs_datetime:
        import_lines.append("import datetime")
        import_lines.append("")

    typing_imports: list[str] = []
    if needs_literal:
        typing_imports.append("Literal")
    if typing_imports:
        import_lines.append(f"from typing import {', '.join(sorted(typing_imports))}")
        import_lines.append("")

    pydantic_imports = ["BaseModel"]
    if needs_field:
        pydantic_imports.append("Field")
    import_lines.append(f"from pydantic import {', '.join(pydantic_imports)}")
    import_lines.append("")
    import_lines.append("")

    # ---- Build class ----
    doc = contract.description or f"Contract {contract.name!r} v{contract.version}."
    class_lines = [
        f"class {class_name}(BaseModel):",
        f'    """{doc}"""',
        "",
    ] + field_lines

    return "\n".join(import_lines + class_lines) + "\n"


# ---------------------------------------------------------------------------
# Live model (runtime)
# ---------------------------------------------------------------------------


def to_pydantic_model(contract: DataContract) -> type:
    """Return a live Pydantic ``BaseModel`` class built from *contract*.

    Requires pydantic to be installed::

        pip install pydantic

    Unlike :func:`to_pydantic_source`, this builds the model in memory using
    :func:`pydantic.create_model`, so no file I/O is involved.  Useful for
    runtime validation of API payloads or event messages.

    Example::

        Order = to_pydantic_model(orders_contract)
        order = Order(order_id=1, amount=99.99, status="COMPLETED")
    """
    try:
        from pydantic import create_model
    except ImportError as exc:
        raise ImportError("Pydantic is required. Install with: pip install pydantic") from exc

    class_name = _to_class_name(contract.name)
    fields_dict: dict[str, Any] = {}

    for col_name, field in contract.schema.items():
        python_type, default = _type_and_default(field)
        fields_dict[col_name] = (python_type, default)

    doc = contract.description or f"Contract {contract.name!r} v{contract.version}."
    model: type = create_model(class_name, __doc__=doc, **fields_dict)
    return model


# ---------------------------------------------------------------------------
# Private helpers — shared
# ---------------------------------------------------------------------------


def _to_class_name(name: str) -> str:
    """Convert a snake_case or hyphen-case name to CamelCase."""
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_"))


def _get_base_annotation(field: Field) -> str:
    """Return the base Python type annotation string for *field*."""
    from datalasi.core.types import (
        Boolean,
        Date,
        Enum,
        Float64,
        Int32,
        Int64,
        String,
        Timestamp,
    )

    t = field.type
    if isinstance(t, (Int64, Int32)):
        return "int"
    if isinstance(t, Float64):
        return "float"
    if isinstance(t, String):
        return "str"
    if isinstance(t, Boolean):
        return "bool"
    if isinstance(t, Date):
        return "datetime.date"
    if isinstance(t, Timestamp):
        return "datetime.datetime"
    if isinstance(t, Enum):
        vals = ", ".join(repr(v) for v in t.allowed_values)
        return f"Literal[{vals}]"
    return "str"


def _get_field_kwargs(field: Field) -> dict[str, Any]:
    """Return keyword arguments for the Pydantic ``Field(...)`` call."""
    from datalasi.core.types import Float64, Int32, Int64, String

    kwargs: dict[str, Any] = {}
    if field.description:
        kwargs["description"] = field.description
    t = field.type
    if isinstance(t, (Int64, Int32, Float64)):
        if t.min is not None:
            kwargs["ge"] = t.min
        if t.max is not None:
            kwargs["le"] = t.max
    if isinstance(t, String):
        if t.max_length is not None:
            kwargs["max_length"] = t.max_length
        if t.pattern is not None:
            kwargs["pattern"] = t.pattern
    return kwargs


# ---------------------------------------------------------------------------
# Private helpers — source generation
# ---------------------------------------------------------------------------


def _annotation_and_default(field: Field) -> tuple[str, str | None]:
    """Return ``(annotation_str, default_expr_str_or_None)`` for source gen."""
    base = _get_base_annotation(field)
    kwargs = _get_field_kwargs(field)
    annotation = f"{base} | None" if field.nullable else base

    if kwargs:
        kw_str = ", ".join(
            f"{k}={v!r}" if isinstance(v, str) else f"{k}={v}" for k, v in kwargs.items()
        )
        default = f"Field(None, {kw_str})" if field.nullable else f"Field(..., {kw_str})"
    elif field.nullable:
        default = "None"
    else:
        default = None  # bare annotation — Pydantic treats as required

    return annotation, default


# ---------------------------------------------------------------------------
# Private helpers — runtime model
# ---------------------------------------------------------------------------


def _type_and_default(field: Field) -> tuple[Any, Any]:
    """Return ``(python_type, pydantic_default)`` for ``create_model``."""
    from pydantic import Field

    try:
        from typing import Optional
    except ImportError:
        Optional = None  # type: ignore[assignment]

    base_type = _get_base_type(field)
    kwargs = _get_field_kwargs(field)

    if field.nullable:
        python_type = Optional[base_type]
        default = Field(None, **kwargs) if kwargs else None
    else:
        python_type = base_type
        default = Field(..., **kwargs) if kwargs else ...

    return python_type, default


def _get_base_type(field: Field) -> Any:
    """Return the actual Python *type* object for *field*."""
    import datetime
    from typing import Literal

    from datalasi.core.types import (
        Boolean,
        Date,
        Enum,
        Float64,
        Int32,
        Int64,
        String,
        Timestamp,
    )

    t = field.type
    if isinstance(t, (Int64, Int32)):
        return int
    if isinstance(t, Float64):
        return float
    if isinstance(t, String):
        return str
    if isinstance(t, Boolean):
        return bool
    if isinstance(t, Date):
        return datetime.date
    if isinstance(t, Timestamp):
        return datetime.datetime
    if isinstance(t, Enum):
        return Literal[tuple(t.allowed_values)]
    return str
