"""Unit tests for Pydantic model generation."""

from __future__ import annotations

import pytest

from datalasi import DataContract, Enum, Field, Float64, Int32, Int64, String
from datalasi.core.types import Boolean, Date, Timestamp
from datalasi.export.pydantic_model import _to_class_name, to_pydantic_source


@pytest.fixture
def contract():
    return DataContract(
        name="orders",
        version="1.0.0",
        description="Customer orders",
        schema={
            "order_id": Field("order_id", Int64(), pk=True, nullable=False),
            "amount": Field(
                "amount", Float64(min=0.01, max=1e6), nullable=False, description="Order amount"
            ),
            "status": Field("status", Enum(["OPEN", "CLOSED", "CANCELLED"]), nullable=False),
            "note": Field("note", String(max_length=500)),
            "quantity": Field("quantity", Int32(), nullable=False),
        },
    )


class TestClassName:
    def test_simple_name(self):
        assert _to_class_name("orders") == "Orders"

    def test_snake_case(self):
        assert _to_class_name("user_orders") == "UserOrders"

    def test_hyphen(self):
        assert _to_class_name("user-orders") == "UserOrders"

    def test_multi_word(self):
        assert _to_class_name("transaction_line_items") == "TransactionLineItems"


class TestSourceOutput:
    def test_returns_string(self, contract):
        src = to_pydantic_source(contract)
        assert isinstance(src, str)

    def test_has_class_definition(self, contract):
        src = to_pydantic_source(contract)
        assert "class Orders(BaseModel):" in src

    def test_has_pydantic_import(self, contract):
        src = to_pydantic_source(contract)
        assert "from pydantic import" in src
        assert "BaseModel" in src

    def test_has_future_annotations(self, contract):
        src = to_pydantic_source(contract)
        assert "from __future__ import annotations" in src

    def test_auto_generated_comment(self, contract):
        src = to_pydantic_source(contract)
        assert "Auto-generated by datalasi" in src

    def test_docstring_from_description(self, contract):
        src = to_pydantic_source(contract)
        assert "Customer orders" in src

    def test_int64_field(self, contract):
        src = to_pydantic_source(contract)
        assert "order_id: int" in src

    def test_float_with_constraints(self, contract):
        src = to_pydantic_source(contract)
        assert "ge=0.01" in src
        assert "le=1000000.0" in src

    def test_enum_becomes_literal(self, contract):
        src = to_pydantic_source(contract)
        assert "Literal" in src
        assert "'OPEN'" in src or '"OPEN"' in src

    def test_nullable_field_has_none_default(self, contract):
        src = to_pydantic_source(contract)
        assert "note: str | None" in src

    def test_non_nullable_has_no_default(self, contract):
        src = to_pydantic_source(contract)
        # order_id is non-nullable with no constraints — should be bare annotation
        assert "order_id: int\n" in src or "order_id: int = Field(...)" in src

    def test_string_max_length_in_field(self, contract):
        src = to_pydantic_source(contract)
        assert "max_length=500" in src

    def test_field_description_included(self, contract):
        src = to_pydantic_source(contract)
        assert "Order amount" in src

    def test_int32_field(self, contract):
        src = to_pydantic_source(contract)
        assert "quantity: int" in src

    def test_boolean_type(self):
        c = DataContract(
            name="t",
            version="1.0.0",
            schema={"active": Field("active", Boolean(), nullable=False)},
        )
        src = to_pydantic_source(c)
        assert "active: bool" in src

    def test_date_type(self):
        c = DataContract(
            name="t",
            version="1.0.0",
            schema={"dt": Field("dt", Date(), nullable=False)},
        )
        src = to_pydantic_source(c)
        assert "import datetime" in src
        assert "datetime.date" in src

    def test_timestamp_type(self):
        c = DataContract(
            name="t",
            version="1.0.0",
            schema={"ts": Field("ts", Timestamp(), nullable=False)},
        )
        src = to_pydantic_source(c)
        assert "datetime.datetime" in src

    def test_convenience_method_on_contract(self, contract):
        assert contract.to_pydantic() == to_pydantic_source(contract)

    def test_source_is_valid_python(self, contract):
        src = to_pydantic_source(contract)
        # Should compile without errors
        compile(src, "<string>", "exec")


class TestLiveModel:
    pydantic = pytest.importorskip("pydantic", reason="pydantic not installed")

    def test_returns_a_class(self, contract):
        from datalasi.export.pydantic_model import to_pydantic_model

        Model = to_pydantic_model(contract)
        assert isinstance(Model, type)

    def test_class_name(self, contract):
        from datalasi.export.pydantic_model import to_pydantic_model

        Model = to_pydantic_model(contract)
        assert Model.__name__ == "Orders"

    def test_valid_instance(self, contract):
        from datalasi.export.pydantic_model import to_pydantic_model

        Model = to_pydantic_model(contract)
        obj = Model(order_id=1, amount=99.99, status="OPEN", quantity=3)
        assert obj.order_id == 1
        assert obj.note is None

    def test_invalid_raises(self, contract):
        from pydantic import ValidationError

        from datalasi.export.pydantic_model import to_pydantic_model

        Model = to_pydantic_model(contract)
        with pytest.raises(ValidationError):
            Model(order_id="not-an-int", amount=99.99, status="OPEN", quantity=1)

    def test_convenience_method(self, contract):
        Model = contract.to_pydantic_model()
        assert Model.__name__ == "Orders"
